/// <reference types="bun-types" />
/**
 * Tenant-scoped Prisma model registry — automated coverage test.
 *
 * PROBLEM this test prevents:
 *   A developer adds a new Prisma model with a `tenantId` field but
 *   forgets to add that model to the `TENANT_SCOPED_MODELS` registry
 *   in `src/lib/db.ts`. The fail-closed Proxy + the Prisma query
 *   extension ONLY cover models in that registry — an unregistered
 *   tenant-scoped model is silently queryable WITHOUT a tenant scope,
 *   which is a tenant-isolation hole.
 *
 * SOLUTION:
 *   Use Prisma's generated structured metadata (the DMMF —
 *   `Prisma.dmmf.datamodel.models`) to enumerate EVERY model in the
 *   schema and find the ones that have a scalar `tenantId` field.
 *   Prove that set equals the `TENANT_SCOPED_MODEL_NAMES` registry
 *   in `src/lib/db.ts`. If a future model addition changes either
 *   side, this test fails automatically.
 *
 * This is NOT a regex over `schema.prisma` — it uses Prisma's own
 * structured model representation (DMMF), which is the same metadata
 * the Prisma engine itself uses. It is robust to formatting changes,
 * comments, and field-ordering.
 *
 * Reverse direction:
 *   A model listed as tenant-scoped should actually contain a
 *   scalar `tenantId` field in the schema. Catches the opposite
 *   mistake — adding a model to the registry that has no `tenantId`
 *   (which would silently route it through the per-tenant client
 *   with NO scope injection, since the handlers are only emitted
 *   for models with `tenantId` in scope).
 *
 * SPECIAL CASE: `DepartmentMember` is a deliberately EXCLUDED model
 * — it has `departmentId` + `userId` (no `tenantId`), so it MUST NOT
 * be in the registry. The test asserts this explicitly so a future
 * developer cannot sneak it in to "satisfy" some other constraint.
 */

import { test, expect } from 'bun:test'
import { Prisma } from '@prisma/client'
import { TENANT_SCOPED_MODEL_NAMES } from '../../src/lib/db'

/**
 * DMMF = Documented Model Metadata Format — Prisma's structured
 * representation of the schema. Generated by `prisma generate` and
 * available at runtime via `Prisma.dmmf.datamodel.models`. Each model
 * has `name` + `fields[]` where each field has `name`, `kind`
 * ('scalar' | 'object' | 'enum' | ...), `type` (e.g. 'String'),
 * `isList`, `isRequired`, etc.
 *
 * For our purposes, a "tenant-scoped model" is one with a scalar
 * field named `tenantId` of type `String`. (We do not require it to
 * be required; some models have it optional. We just require the
 * scalar field to exist.)
 */
const dmmfModels = Prisma.dmmf.datamodel.models

/** All model names in the schema, sorted. */
const allModelNames: string[] = dmmfModels.map(m => m.name).sort()

/** Models with a scalar `tenantId` field, sorted. */
const modelsWithTenantIdScalar: string[] = dmmfModels
  .filter(m => m.fields.some(f =>
    f.name === 'tenantId' &&
    f.kind === 'scalar' &&
    (f as any).type === 'String'
  ))
  .map(m => m.name)
  .sort()

/** The canonical registry from src/lib/db.ts, sorted. */
const registryNames: string[] = [...TENANT_SCOPED_MODEL_NAMES].sort()

test('Prisma DMMF is available (sanity check on the metadata source)', () => {
  // If Prisma ever changes the DMMF shape, this is the test that fails
  // first with a clear message, rather than the deeper assertions
  // failing with a confusing "cannot read .fields of undefined".
  expect(dmmfModels, 'Prisma.dmmf.datamodel.models must be an array').toBeInstanceOf(Array)
  expect(dmmfModels.length, 'schema must declare at least 10 models').toBeGreaterThanOrEqual(10)
})

test('TENANT_SCOPED_MODEL_NAMES is a frozen, non-mutable registry', () => {
  // The registry must be exported as a readonly, frozen array —
  // application code must NOT be able to mutate it at runtime.
  expect(Array.isArray(TENANT_SCOPED_MODEL_NAMES)).toBe(true)
  expect(Object.isFrozen(TENANT_SCOPED_MODEL_NAMES), 'registry must be Object.frozen').toBe(true)
  // Attempting to push / splice / assign must NOT change the array.
  // Object.freeze makes array-length-mutation methods throw in strict
  // mode; in non-strict mode they silently fail. Either way the
  // original content is unchanged.
  const original = [...TENANT_SCOPED_MODEL_NAMES]
  expect(() => { (TENANT_SCOPED_MODEL_NAMES as any).push('ShouldNotWork') }).toThrow()
  expect([...TENANT_SCOPED_MODEL_NAMES]).toEqual(original)
})

test('Every Prisma model with a scalar tenantId is in the registry', () => {
  // The set of models-with-tenantId must be a SUBSET of the registry.
  // Any model with a scalar tenantId that is NOT in the registry is
  // an automatic fail-closed hole — that model would be queryable
  // without a tenant scope.
  const missingFromRegistry = modelsWithTenantIdScalar.filter(name => !registryNames.includes(name))
  expect(
    missingFromRegistry,
    `Models with a scalar tenantId field missing from TENANT_SCOPED_MODEL_NAMES: ${JSON.stringify(missingFromRegistry)}. These models are NOT covered by the fail-closed tenant-scoping Proxy or the Prisma query extension — they are queryable without a tenant scope, which is a tenant-isolation hole. Add them to TENANT_SCOPED_MODEL_NAMES in src/lib/db.ts.`,
  ).toEqual([])
})

test('Every model in the registry has a scalar tenantId in the schema', () => {
  // Reverse direction: any model listed as tenant-scoped should
  // actually have a scalar `tenantId` in the schema. A registry
  // entry with no matching schema field is dead code — the handlers
  // would silently route it through the per-tenant client with NO
  // scope injection (because there's no tenantId to inject).
  const orphans = registryNames.filter(name => !modelsWithTenantIdScalar.includes(name))
  expect(
    orphans,
    `Registry entries with NO matching scalar tenantId in the schema: ${JSON.stringify(orphans)}. These models are listed in TENANT_SCOPED_MODEL_NAMES but have no scalar tenantId field — they are dead-registry entries that route through the per-tenant client with NO scope injection. Remove them from TENANT_SCOPED_MODEL_NAMES or add a scalar tenantId field to their schema definition.`,
  ).toEqual([])
})

test('The registry set and the schema set are exactly equal (no diff either way)', () => {
  // The two sets must be EQUAL — neither a subset nor a superset.
  // This is the strong invariant. If either side changes without the
  // other, this test fails with a clean diff.
  expect(registryNames).toEqual(modelsWithTenantIdScalar)
})

test('DepartmentMember is NOT in the registry (it has no tenantId)', () => {
  // DepartmentMember is the explicitly-discussed special case. It
  // has `departmentId` + `userId` (no scalar tenantId) — so it MUST
  // NOT be in the tenant-scoping registry. It is enforced SEPARATELY
  // via the boundary checks in src/lib/department-members.ts
  // (foreign-department / foreign-user / inactive-user rejections).
  //
  // A future developer who adds it to the registry "to satisfy some
  // other test" would actually WEAKEN isolation (the per-tenant
  // client would route through it with NO scope injection, since
  // there's no tenantId field to inject). This test makes that
  // mistake automatically detectable.
  expect(TENANT_SCOPED_MODEL_NAMES).not.toContain('DepartmentMember')
  // And confirm the schema does not give it a scalar tenantId.
  const dm = dmmfModels.find(m => m.name === 'DepartmentMember')
  expect(dm, 'DepartmentMember model must exist in the schema').toBeDefined()
  const hasTenantIdField = dm!.fields.some(f => f.name === 'tenantId' && f.kind === 'scalar')
  expect(hasTenantIdField, 'DepartmentMember must NOT have a scalar tenantId field').toBe(false)
})

test('Reverse direction sanity: the registry does not contain unknown model names', () => {
  // Every registry name must be a real model in the Prisma schema.
  // A typo (e.g. 'Converation' instead of 'Conversation') would
  // silently do nothing — the handlers would be emitted for a
  // delegate key that doesn't exist, with no error.
  const unknown = registryNames.filter(name => !allModelNames.includes(name))
  expect(
    unknown,
    `Registry entries that do not exist as Prisma models: ${JSON.stringify(unknown)}. These are typos or stale entries — fix or remove them.`,
  ).toEqual([])
})

test('All expected tenant-scoped models are present (snapshot of the known set)', () => {
  // A snapshot of the current known set, for documentation + a
  // clear failure if a model is accidentally removed. If a model is
  // INTENTIONALLY added or removed, this snapshot is the place to
  // update — and the test above will already have failed with a
  // clearer "missing from registry" or "orphaned entry" message.
  expect(modelsWithTenantIdScalar).toEqual([
    'AiConfig',
    'ConnectorConfig',
    'Contact',
    'Conversation',
    'Department',
    'FaqPair',
    'Invoice',
    'Membership',
    'Message',
    'Participant',
    'Product',
    'RoutingRule',
    'Subscription',
    'WidgetConfig',
    'WidgetDomain',
  ])
})
